---
# vars file for kvm_provisioning
vm_name: deleteme
vm_ram_mb: 2048
vm_vcpus: 2
vm_root_password: "redhat2023"
libvirt_pool_dir: /var/lib/libvirt/images
vm_net: vmnetwork
template_image_file: appliance.qcow2
ssh_key: /home/samdiament/.ssh/id_rsa.pub