---
# playbook to execute kvm_provision role
- name: Deploys VM based on cloud image
  hosts: all
  gather_facts: yes
  vars:
    libvirtPoolDir: "/home/samdiament/.local/share/libvirt/images"
    vmName: deleteme
    vmVcpus: 2
    vmRamMb: 2048
    cleanupTmp: no
    vmNet: vmnetwork
    sshPubKey: "/home/samdiament/.ssh/id_rsa.pub"

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        libvirtPoolDir: "{{ libvirtPoolDir }}"
        vmName: "{{ vmName }}"
        vmVcpus: "{{ vmName }}"
        vmRamMb: "{{ vmRamMb }}"
        vmNet: "{{ vmNet }}"
        cleanupTmp: "{{ cleanupTmp }}"
        sshKey: "{{ sshPubKey }}"